module.exports = {
  content: ["./code.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        tertiary: "#000000",
        "on-secondary-fixed": "#281801",
        "tertiary-container": "#1b1c1c",
        "surface-container": "#efeeeb",
        "inverse-primary": "#c6c6c6",
        "outline-variant": "#cfc4c5",
        "on-primary-fixed-variant": "#474747",
        "secondary-fixed-dim": "#e1c299",
        "on-secondary-fixed-variant": "#584324",
        "tertiary-fixed-dim": "#c8c6c6",
        "surface-variant": "#e3e2e0",
        "on-secondary-container": "#765f3d",
        "inverse-on-surface": "#f2f1ee",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        primary: "#000000",
        "on-tertiary-fixed": "#1b1c1c",
        "tertiary-fixed": "#e4e2e1",
        "on-primary": "#ffffff",
        "secondary-fixed": "#feddb3",
        "on-primary-fixed": "#1b1b1b",
        surface: "#faf9f6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e2e2e2",
        "inverse-surface": "#2f312f",
        "on-tertiary-fixed-variant": "#474747",
        background: "#faf9f6",
        "surface-tint": "#5e5e5e",
        "on-surface-variant": "#4c4546",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e3e2e0",
        "on-background": "#1a1c1a",
        error: "#ba1a1a",
        "surface-container-high": "#e9e8e5",
        secondary: "#725a39",
        "on-tertiary-container": "#858383",
        "on-secondary": "#ffffff",
        "on-primary-container": "#848484",
        "surface-container-low": "#f4f3f1",
        "on-surface": "#1a1c1a",
        "primary-fixed-dim": "#c6c6c6",
        "secondary-container": "#fbdbb0",
        outline: "#7e7576",
        "surface-dim": "#dbdad7",
        "surface-bright": "#faf9f6",
        "primary-container": "#1b1b1b",
        "on-tertiary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "8px",
        "margin-desktop": "64px",
        "container-max-width": "1280px",
        "section-padding": "80px",
        gutter: "24px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        h2: ["Manrope"],
        h1: ["Manrope"],
        "body-md": ["Manrope"],
        "body-lg": ["Manrope"],
        "label-caps": ["IBM Plex Mono"],
        display: ["Manrope"],
        h3: ["Manrope"],
      },
      fontSize: {
        h2: ["32px", { lineHeight: "1.3", letterSpacing: "0em", fontWeight: "500" }],
        h1: ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.8", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.15em", fontWeight: "700" }],
        display: ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        h3: ["24px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "600" }],
      },
    },
  },
};
